### ISSUE TITLE
Python syntax error

### ISSUE THREAD

**Issue by soufianekar** [NCAR/CVDP-LE#12]
Parentheses missing from the print() function.
https://github.com/NCAR/CVDP-LE/blob/49516a092737894d66533946d611b2fb97625fa1/ncl_scripts/runTasks.py#L56

**Comment by phillips-ad** [comment]
Thank you! I will alter in the next release.

**Comment by phillips-ad** [comment]
Solved in recent commit:
https://github.com/NCAR/CVDP-LE/commit/473b97efbad6a645b7382dd1323640062e0463c1
